"""Schema definitions for the backend API's Supabase Postgres database:
users (both roles), tickets, the persisted message thread, and the audit
trail. These are Alembic's source of truth for autogenerating migrations
(see alembic/env.py) - the running app never queries through these classes,
it goes through backend/supabase_client.py's Supabase client instead, so
there are no relationship()/cascade declarations here, and every default
below is a real database-level default/trigger rather than a Python-side
ORM default - the app's inserts/updates go straight to PostgREST, so a
Python `default=`/`onupdate=` callable (which only SQLAlchemy's own ORM
insert path would ever evaluate) would silently never fire. Cascading
deletes (ticket -> its messages/activity), `created_at`/`updated_at`
timestamps, and `ticket_number` generation are all enforced in Postgres
itself (see the "cascade deletes and ticket number trigger" and
"server-side defaults and updated_at triggers" migrations).

Category/priority/department values are validated at the Pydantic schema
layer (backend/schemas.py) against the existing ticket_router.models
Literals - they're plain strings here since SQLAlchemy's Enum type would
need updating every time a category is added, and that validation already
lives in one place.

Role/TicketStatus/SenderType *are* real Python enums (validated by
Pydantic), but are declared with native_enum=False so they're stored as
VARCHAR + a CHECK constraint instead of a Postgres native enum type -
Alembic autogenerate can't detect new values added to a native Postgres
enum, which would otherwise require a hand-written migration.
"""

from datetime import datetime
from enum import StrEnum

from sqlalchemy import JSON, DateTime, Enum, Float, ForeignKey, String, Text, func, text
from sqlalchemy.orm import Mapped, mapped_column

from backend.db import Base


class Role(StrEnum):
    USER = "USER"
    ADMIN = "ADMIN"


class TicketStatus(StrEnum):
    NEW = "NEW"
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    PENDING_CUSTOMER = "PENDING_CUSTOMER"
    ON_HOLD = "ON_HOLD"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class SenderType(StrEnum):
    USER = "USER"
    ADMIN = "ADMIN"
    AI = "AI"


class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(200))
    email: Mapped[str] = mapped_column(String(320), unique=True, index=True)
    password_hash: Mapped[str] = mapped_column(String(200))
    role: Mapped[Role] = mapped_column(
        Enum(Role, native_enum=False),
        server_default=text("'USER'"),
        nullable=False,
    )
    # Only meaningful for ADMIN rows: the one team this admin can see. NULL
    # means a super-admin with visibility into every team. Always NULL for
    # USER rows.
    department: Mapped[str | None] = mapped_column(String(50), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    # Initial value only - kept current on every UPDATE by a DB trigger (see
    # the "server-side defaults and updated_at triggers" migration), since
    # there's no ORM onupdate= hook once queries go through the Supabase
    # client.
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


class Ticket(Base):
    __tablename__ = "tickets"

    id: Mapped[int] = mapped_column(primary_key=True)
    # Generated by a Postgres trigger (see the "cascade deletes and ticket
    # number trigger" migration), not the app - a BEFORE INSERT trigger sets
    # this from the row's own id, since there's no app-level flush-then-
    # derive step once queries go through the Supabase client (a plain HTTP
    # request per call, no partial-transaction concept).
    ticket_number: Mapped[str] = mapped_column(String(20), unique=True, index=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"), nullable=False)
    title: Mapped[str] = mapped_column(String(200))
    description: Mapped[str] = mapped_column(Text)
    department: Mapped[str] = mapped_column(String(50))
    priority: Mapped[str] = mapped_column(String(20))
    status: Mapped[TicketStatus] = mapped_column(
        Enum(TicketStatus, native_enum=False),
        server_default=text("'NEW'"),
        nullable=False,
    )
    assigned_admin_id: Mapped[int | None] = mapped_column(ForeignKey("users.id"), nullable=True)
    ai_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    ai_category: Mapped[str | None] = mapped_column(String(50), nullable=True)
    ai_emotion: Mapped[str | None] = mapped_column(String(20), nullable=True)
    ai_confidence: Mapped[float | None] = mapped_column(Float, nullable=True)
    # The AI's own priority suggestion, immutable once set - kept separate
    # from the mutable `priority` column above (which starts out equal to
    # this, but can be overridden by the customer at creation time or
    # reassigned by an admin later) so the UI can show "AI suggested X, you
    # chose Y" the way the original Router tab did.
    ai_priority: Mapped[str | None] = mapped_column(String(20), nullable=True)
    # How long the route_ticket() call itself took, in milliseconds - shown
    # against an admin's own manual-triage time in the admin dashboard's
    # "Manual Routing" comparison panel.
    ai_processing_ms: Mapped[float | None] = mapped_column(Float, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    # Initial value only - kept current on every UPDATE by a DB trigger, see
    # User.updated_at above.
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    closed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


class TicketMessage(Base):
    __tablename__ = "ticket_messages"

    id: Mapped[int] = mapped_column(primary_key=True)
    # ondelete="CASCADE": deleting a ticket deletes its messages at the DB
    # level - there's no ORM session to cascade this the way SQLAlchemy's
    # relationship(cascade="all, delete-orphan") used to.
    ticket_id: Mapped[int] = mapped_column(
        ForeignKey("tickets.id", ondelete="CASCADE"), nullable=False
    )
    sender_type: Mapped[SenderType] = mapped_column(
        Enum(SenderType, native_enum=False), nullable=False
    )
    # NULL for AI-authored messages; set for USER/ADMIN messages.
    sender_id: Mapped[int | None] = mapped_column(ForeignKey("users.id"), nullable=True)
    message: Mapped[str] = mapped_column(Text)
    # Reserved for future file-upload support - no upload UI/endpoint yet.
    attachments: Mapped[list | None] = mapped_column(JSON, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


class TicketActivity(Base):
    __tablename__ = "ticket_activity"

    id: Mapped[int] = mapped_column(primary_key=True)
    ticket_id: Mapped[int] = mapped_column(
        ForeignKey("tickets.id", ondelete="CASCADE"), nullable=False
    )
    event_type: Mapped[str] = mapped_column(String(50))
    detail: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
