"""add indexes for date-range filtering

Revision ID: 465451ae242e
Revises: 98a018330e2a
Create Date: 2026-07-22 15:38:39.346543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '465451ae242e'
down_revision: Union[str, Sequence[str], None] = '98a018330e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_survey_answers_question_id'), 'survey_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_survey_answers_response_id'), 'survey_answers', ['response_id'], unique=False)
    op.create_index(op.f('ix_survey_responses_submitted_at'), 'survey_responses', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_survey_responses_survey_id'), 'survey_responses', ['survey_id'], unique=False)
    op.create_index(op.f('ix_survey_responses_user_id'), 'survey_responses', ['user_id'], unique=False)
    op.create_index(op.f('ix_tickets_created_at'), 'tickets', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_created_at'), table_name='tickets')
    op.drop_index(op.f('ix_survey_responses_user_id'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_survey_id'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_submitted_at'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_answers_response_id'), table_name='survey_answers')
    op.drop_index(op.f('ix_survey_answers_question_id'), table_name='survey_answers')
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedback')
    # ### end Alembic commands ###
