"""add theme to tickets and feedback

Revision ID: 54d11cf9b09c
Revises: 4343a7aeb8d0
Create Date: 2026-07-22 13:16:43.071212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54d11cf9b09c'
down_revision: Union[str, Sequence[str], None] = '4343a7aeb8d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('theme', sa.String(length=100), nullable=True))
    op.add_column('tickets', sa.Column('theme', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'theme')
    op.drop_column('feedback', 'theme')
    # ### end Alembic commands ###
