"""add ticket ai_reasoning column

Revision ID: 65f22f0ef76d
Revises: 465451ae242e
Create Date: 2026-07-22 16:26:04.518509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f22f0ef76d'
down_revision: Union[str, Sequence[str], None] = '465451ae242e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('ai_reasoning', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'ai_reasoning')
    # ### end Alembic commands ###
