"""add weekly reports table

Revision ID: d4f16233edf1
Revises: 65f22f0ef76d
Create Date: 2026-07-23 10:46:43.799367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4f16233edf1'
down_revision: Union[str, Sequence[str], None] = '65f22f0ef76d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_feedback', sa.Integer(), nullable=False),
    sa.Column('sentiment_breakdown', sa.JSON(), nullable=False),
    sa.Column('top_themes', sa.JSON(), nullable=False),
    sa.Column('overview', sa.Text(), nullable=False),
    sa.Column('overall_sentiment', sa.Text(), nullable=False),
    sa.Column('key_insights', sa.JSON(), nullable=False),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('positive_highlights', sa.JSON(), nullable=False),
    sa.Column('generated_by', sa.String(length=20), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_reports_period_end'), 'weekly_reports', ['period_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_reports_period_end'), table_name='weekly_reports')
    op.drop_table('weekly_reports')
    # ### end Alembic commands ###
