[theme]
base = "dark"
primaryColor = "#f8fafc"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0a0a0a"
textColor = "#f1f5f9"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
